//Last updated: 06/23/2018 17:45 MDT - HN
var map_config = {
	'default':{
		'bordercolor':'#f7f7f7',       // inter-state borders
		'lakescolor':'#b8e8ff',        // lakes color ... originally #66CCFF
		'shadowcolor':'#000000',       // shadow color below the map
		'shadowOpacity':'30',          // shadow opacity, value, 0-100 ... originally 50
		'namescolor':'#ffffff',        // color of the abbreviations 
		'namesShadowColor':'#666666',  // tooltip shadow color
	},
	'map_1':{
		'namesId':'AL',   // State Name's ID (Don't change it since this is used in other files for the map)
		'name': 'Click here! Coaching & Licensing is also available!',   // Text that's displayed when the mouse is over that state
		'url':'https://adres.thoughtindustries.com/pages/alabama',  // URL to go to when you click on the state
		'target':'_blank',      // '_blank' opens the state in the main browser window instead of in the iframe
		'upcolor':'#f4c900',    // Color displayed when the mouse is not over that state
		'overcolor':'#f4a900',  // Color displayed when the mouse is hovering over that state
		'downcolor':'#f4a900',  // Color displayed when the mouse clicks on that state
		'enable':true,          // "true" enables you to click on the state and go to another webpage. "false" deactivates the link.
	},
	'map_2':{
		'namesId':'AK',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/alaska',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
	'map_3':{
		'namesId':'AZ',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/arizona',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
	'map_4':{
		'namesId':'AR',
		'name': 'Click here! Coaching & Licensing is also available!',
		'url':'https://adres.thoughtindustries.com/pages/arkansas',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
	'map_5':{
		'namesId':'CA',
		'name': 'Click here! Coaching & Licensing is also available!',
		'url':'https://adres.thoughtindustries.com/pages/california',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},	
	'map_6':{
		'namesId':'CO',
		'name': 'Click here! Coaching & Licensing is also available!',
		'url':'https://adres.thoughtindustries.com/pages/colorado',
		'target':'_blank',
		'upcolor':'#6fbe44',
		'overcolor':'#3ca900',
		'downcolor':'#3ca900',
		'enable':true,
	},
	'map_7':{
		'namesId':'CT',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/connecticut',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
	'map_8':{
		'namesId':'DE',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/delaware',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},	
	'map_9':{
		'namesId':'FL',
		'name': 'Click here! Coaching & Licensing is also available!',
		'url':'https://adres.thoughtindustries.com/pages/florida',
		'target':'_blank',
		'upcolor':'#6fbe44',
		'overcolor':'#3ca900',
		'downcolor':'#3ca900',
		'enable':true,
	},
	'map_10':{
		'namesId':'GA',
		'name': 'Click here! Coaching & Licensing is also available!',
		'url':'https://adres.thoughtindustries.com/pages/georgia',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
	'map_11':{
		'namesId':'HI',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/hawaii',
		'target':'_blank',
		'upcolor':'#6fbe44',
		'overcolor':'#3ca900',
		'downcolor':'#3ca900',
		'enable':true,
	},	
	'map_12':{
		'namesId':'ID',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/idaho',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
	'map_13':{
		'namesId':'IL',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/illinois',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
	'map_14':{
		'namesId':'IN',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/indiana',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
	'map_15':{
		'namesId':'IA',
		'name': 'Click here! Coaching & Licensing is also available!',
		'url':'https://adres.thoughtindustries.com/pages/iowa',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},	
	'map_16':{
		'namesId':'KS',
		'name': 'Click here! Coaching & Licensing is also available!',
		'url':'https://adres.thoughtindustries.com/pages/kansas',
		'target':'_blank',
		'upcolor':'#6fbe44',
		'overcolor':'#3ca900',
		'downcolor':'#3ca900',
		'enable':true,
	},
	'map_17':{
		'namesId':'KY',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/kentucky',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
	'map_18':{
		'namesId':'LA',
		'name': 'Click here! Coaching & Licensing is also available!',
		'url':'https://adres.thoughtindustries.com/pages/louisiana',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},	
	'map_19':{
		'namesId':'ME',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/maine',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
	'map_20':{
		'namesId':'MD',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/maryland',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
	'map_21':{
		'namesId':'MA',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/massachusetts',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},	
	'map_22':{
		'namesId':'MI',
		'name': 'Click here! Coaching & Licensing is also available!',
		'url':'https://adres.thoughtindustries.com/pages/michigan',
		'target':'_blank',
		'upcolor':'#6fbe44',
		'overcolor':'#3ca900',
		'downcolor':'#3ca900',
		'enable':true,
	},
	'map_23':{
		'namesId':'MN',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/minnesota',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
	'map_24':{
		'namesId':'MS',
		'name': 'Click here! Coaching & Licensing is also available!',
		'url':'https://adres.thoughtindustries.com/pages/mississippi',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
	'map_25':{
		'namesId':'MO',
		'name': 'Click here! Coaching & Licensing is also available!',
		'url':'https://adres.thoughtindustries.com/pages/missouri',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},	
	'map_26':{
		'namesId':'MT',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/montana',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
	'map_27':{
		'namesId':'NE',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/nebraska',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
	'map_28':{
		'namesId':'NV',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/nevada',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},	
	'map_29':{
		'namesId':'NH',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/new-hampshire',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
	'map_30':{
		'namesId':'NJ',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/new-jersey',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
	'map_31':{
		'namesId':'NM',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/new-mexico',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},	
	'map_32':{
		'namesId':'NY',
		'name': 'Click here! Coaching & Licensing is also available!',
		'url':'https://adres.thoughtindustries.com/pages/new-york',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
	'map_33':{
		'namesId':'NC',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/north-carolina',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
	'map_34':{
		'namesId':'ND',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/north-dakota',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
	'map_35':{
		'namesId':'OH',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/ohio',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},	
	'map_36':{
		'namesId':'OK',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/oklahoma',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
	'map_37':{
		'namesId':'OR',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/oregon',
		'target':'_blank',
		'upcolor':'#6fbe44',
		'overcolor':'#3ca900',
		'downcolor':'#3ca900',
		'enable':true,
	},
	'map_38':{
		'namesId':'PA',
		'name': 'Click here! Coaching & Licensing is also available!',
		'url':'https://adres.thoughtindustries.com/pages/pennsylvania',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},	
	'map_39':{
		'namesId':'RI',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/rhode-island',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
	'map_40':{
		'namesId':'SC',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/south-carolina',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
	'map_41':{
		'namesId':'SD',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/south-dakota',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},	
	'map_42':{
		'namesId':'TN',
		'name': 'Click here! Coaching & Licensing is also available!',
		'url':'https://adres.thoughtindustries.com/pages/tennessee',
		'target':'_blank',
		'upcolor':'#6fbe44',
		'overcolor':'#3ca900',
		'downcolor':'#3ca900',
		'enable':true,
	},
	'map_43':{
		'namesId':'TX',
		'name': 'Click here! Coaching & Licensing is also available!',
		'url':'https://adres.thoughtindustries.com/pages/texas',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
	'map_44':{
		'namesId':'UT',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/utah',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
	'map_45':{
		'namesId':'VT',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/vermont',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},	
	'map_46':{
		'namesId':'VA',
		'name': 'Click here! Coaching & Licensing is also available!',
		'url':'https://adres.thoughtindustries.com/pages/virginia',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
	'map_47':{
		'namesId':'WA',
		'name': 'Click here! Coaching & Licensing is also available!',
		'url':'https://adres.thoughtindustries.com/pages/washington',
		'target':'_blank',
		'upcolor':'#6fbe44',
		'overcolor':'#3ca900',
		'downcolor':'#3ca900',
		'enable':true,
	},
	'map_48':{
		'namesId':'WV',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/west-virginia',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},	
	'map_49':{
		'namesId':'WI',
		'name': 'Click here! Coaching & Licensing is also available!',
		'url':'https://adres.thoughtindustries.com/pages/wisconsin',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
	'map_50':{
		'namesId':'WY',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/wyoming',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
	'map_51':{
		'namesId':'DC',
		'name': 'Click here! Coaching is also available!',
		'url':'https://adres.thoughtindustries.com/pages/washington-dc',
		'target':'_blank',
		'upcolor':'#f4c900',
		'overcolor':'#f4a900',
		'downcolor':'#f4a900',
		'enable':true,
	},
}